---
title: "Analysing individual specialisation and flexibility in predator hunting mode and its effect on hunting success using an online multiplayer videogame"
author: "Maxime Fraser Franco^1^, Francesca Santostefano^1^, Clint D. Kelly^1^, Pierre-Olivier Montiglio^1^"
output: 
  word_document:
    reference_docx: Chapter2-styles.docx
bibliography: references.bib
csl: e-letters.csl
---
###### Groupe de Recherche en Écologie Comportementale et Animale (GRECA), Département des Sciences Biologiques, Université du Québec à Montréal, Montréal, QC, Canada
  
###### ^1^Correspondence: Pavillon des Sciences Biologiques (SB) SB-1805, 141 Avenue du Président-Kennedy, Montréal (Québec), Canada, H2X 1Y4

###### ^1^Corresponding author: maxime(dot)fraser(dot)franco(at)hotmail.com


\newpage
# Abstract {.unnumbered}
This is my abstract paragraph

Keywords: individual variation, hunting success, foraging mode, hunting tactics, predator-prey behaviour, online videogames

\newpage
# Introduction {.unnumbered}

Predator hunting mode plays a crucial role in structuring ecological communities and ecosystems [@hueyEcologicalConsequencesForaging1981; @preisserPredatorHuntingMode2007; @schmitzEffectsPredatorHunting2008; @romeroContrastingCascadeEffects2011; @kersch-beckerCommunitywideResponsesPredation2018]. Experimental studies in the field show that contrasting hunting modes, such as active vs sit-and-wait hunting, can cause opposing trophic cascades and act at different trophic levels [@schmitzEffectsPredatorHunting2008]. For instance, predators may differ in the amount of individuals, species, or in the type of prey they capture relative to their hunting mode [@donihueAegeanWallLizards2016; @glaudasForagingModeRelative2019; @millerFearMovePredator2014]. Predator hunting modes are classified in three categories: 1) Active/patrolling hunters who usually search, follow, and chase prey on long distances, 2) sit-and-pursue hunters who remain motionless and pounce on prey that are within chasing distance, and 3) sit-and-wait (ambush) hunters who wait for prey to be within immediate capture distance [@mclaughlinSearchModesBirds1989]. There has recently been a growing interest in investigating how ecological factors shape individual variation in hunting behaviour within populations, and its consequences for predator-prey interactions [@pettorelliChapterTwoIndividual2015; @toscanoPersonalityForagingBehavior2016; @schmitzPredatorPreyFunctional2017]. Experimental evidence show that individual predator behavioural type can mediate consumptive and nonconsumptive effects during trophic interactions [@preisserPredatorHuntingMode2007; @griffenRoleIndividualBehavior2012; @toscanoTraitmediatedFunctionalResponses2014]. However, empirical studies still tend to classify predator species either as active or sit-and-wait hunters based on their average behaviour [@bolnickWhyIntraspecificTrait2011; @pettorelliChapterTwoIndividual2015; @schmitzPredatorPreyFunctional2017]. Thus, accounting for individual variation in hunting mode is a pressing need if we aim to understand the community consequences of predation.

Individual variation in hunting mode can be driven by specialisation when predators in a given population display consistent differences in their tactic use. Such differences are expected when individuals experience temporal and/or spatial fluctuations in the distribution, the availability, or the behaviour of their prey [@araujoEcologicalCausesIndividual2011; @carneiroMethodsDetectingQuantifying2017; @courbinShorttermPreyField2018; @phillipsCausesConsequencesIndividual2017]. For example, prey activity/mobility level is an important mediator of encounter rates with predators [@gerritsenEncounterProbabilitiesCommunity1977; @hueyEcologicalConsequencesForaging1981; @scharfEfficiencyEvaluationTwo2006]. Hence, predators may specialise by using specific hunting modes to meet the energy/time required to successfully capture the type of prey they encounter. In this sense, the locomotor-crossover hypothesis [@hueyEcologicalConsequencesForaging1981] predicts that ambush predators should be more sucessful when they hunt fast-moving prey, while active predators should have greater success with sedentary prey [@belgradPredatorPreyInteractions2016; @donihueAegeanWallLizards2016; @scharfEfficiencyEvaluationTwo2006]. If the individuals' tactics allow them to reach similar capture rates, then predators with contrasting hunting modes may coexist within the same population [@koblerCoexistenceBehaviouralTypes2009; @michelDifferentialEffectsStructural2009; @changPredatorPersonalityPrey2017]. However, it may be difficult to test such an hypothesis at the individual level in wild populations of free ranging predators.

Habitat structure is a second important driver of individual differences in predator foraging mode, as it shapes opportunities of prey encounter and prey capture [@donihueAegeanWallLizards2016; @jamesEffectsHabitatComplexity1994; @robinsonForagingBehaviorForest1982; @sargeantCanEnvironmentalHeterogeneity2007; @wasiolkaBehaviouralResponsesLizard2009]. Hence, habitat caracteristics could be used to predict the tactic a predator should use. A growing body of evidence points that predators who hunt in open and homogeneous habitats tend to adopt an active mode, contrary to those hunting in heterogeneous and closed habitats who adopt an ambush strategy [@donihueAegeanWallLizards2016; @jamesEffectsHabitatComplexity1994; @wasiolkaBehaviouralResponsesLizard2009]. Heterogeneous habitats are expected to favor sit-and-wait/sit-and-pursue hunters as they offer perches and hiding grounds for ambushes [@jamesEffectsHabitatComplexity1994; @laurelInfluenceCruisingAmbush2006]. On the contrary, active hunters should benefit from higher encounter rates in open habitats as prey detection is easier, at the expense of being themselves more easily detected [@michelDifferentialEffectsStructural2009].

Ceci implique donc un compromis entre les deux stratégies selon
la situation, et la capacité d’ajustement des prédateurs devrait être critique pour
leur succès face à des conditions environnementales changeantes.


paragraphe switching




# References

<div id="refs"></div>

