---
title: "Online supporting information for Analysing individual specialisation and flexibility in predator hunting mode and its effect on hunting success using an online multiplayer videogame"
author: "Maxime Fraser Franco^1^, Francesca Santostefano^1^, Clint D. Kelly^1^, Pierre-Olivier Montiglio^1^"
output: 
  word_document:
    reference_docx: Chapter2-styles.docx
bibliography: references.bib
csl: american-naturalist.csl
---

###### Groupe de Recherche en Écologie Comportementale et Animale (GRECA), Département des Sciences Biologiques, Université du Québec à Montréal, Montréal, QC, Canada
  
###### ^1^Correspondence: Pavillon des Sciences Biologiques (SB) SB-1805, 141 Avenue du Président-Kennedy, Montréal (Québec), Canada, H2X 1Y4

###### ^1^Corresponding author: maxime(dot)fraser(dot)franco(at)hotmail.com

\newpage
# Appendix S1. Materials and methods {.unnumbered}

## S1.1 Behavioural traits measurements

We quantified average travel speed as the average number of meters per second traveled during a match. For the rate of space covered, grids with squares of 16 m2 covering the entire playable surface area were drawn for all game environments. Similar to the open-field test for rodents (Montiglio et al., 2010), the number of times a predator entered a square on the grid was recorded, however, it was not possible to know which specific square was visited. Based on this data, we could divide the number of times a square was visited by the match duration to obtain the rate of space covered. For the proportion of time spent guarding, circles of 9-meter radiuses were drawn around all places (the circles’ center) where the predator brought prey to be consumed. For each event, the time (in seconds) a predator spent monitoring inside the area of a circle was recorded. We could then sum the amount of time spent guarding during a match and divide it by the total amount of time a match lasted (in seconds) to have the proportion of time spent guarding.

## S1.2 Principal component analysis

We computed the PCA using packages “FactoMineR” (Lê, Josse, & Husson, 2008) and “factoextra” (Kassambara & Mundt, 2017) in the R software version 4.0.4 (R Core Team, 2021), under a Windows 10 computer OS. The “PCA” function in “FactoMineR” uses singular value decomposition. Before running the PCA, we divided each variable (except travel speed) by the match duration to account for differences in duration among matches. All variables were standardized to mean and unit variance (Z scores) prior to running the PCA. We ranked variables based on their contribution (in %) to a given principal component axis using the ratio of their specific cos2 multiplied by 100 with the cos2 of the principal component.

## S1.3 Parametrisation of the multivariate mixed-model

For both models, we used an uninformative inverse-Wishart prior with a belief parameter (nu) set to 2.002 for the random effects and residuals variance-covariance matrixes. We ran both models for 203 000 iterations by sampling every 100 intervals (thinning) and discarded the first 3000 iterations (burn in). We ran the models four times and visually inspected trace plots, effective sample sizes, and residuals to assess convergence and stability. We computed among-individual, environment, avatar, and within-individual variance-covariance matrixes for both multivariate MCMC models. We extracted the among- and within- individual behavioural correlations using function posterior.cor() in the MCMCglmm package. The variance-covariance matrixes were parametrized as such :

*insert equations*

where the diagonals represent the random effect variances for each hunting trait, and the lower off-diagonals the covariance between the random effect intercepts for each combination of hunting traits (travel speed, the rate of space covered, and the proportion of time spent guarding).

# Appendix S2. Results

# S2.1 Principal component analysis

The first principal component (PC1) explained 20.9% of the total variation, and the second principal component (PC2) explained 18.6% of the total variation (Fig. S1). We found that travel speed and prey guarding had the highest contribution to the first principal component (28.31% and 25.41% respectively) (Table SI), while the rate of space covered had the second highest contribution (30.48%) to the second principal component (Table SI). We excluded the number of chases from the subsequent analyses because they are used to calculate the amount of points earned in a match which is our performance proxy. Prey guarding is negatively correlated with travel speed (Fig. S1), which may indicate the presence of structured tactics where individuals that are fast do not guard captured prey and individuals who guard prey are slower travelers.

