---
output: 
  word_document:
    reference_docx: Chapter2-styles.docx
bibliography: references.bib
csl: behav-ecol.csl

header-includes:
  \usepackage{amsmath}
---

**Title:** Studying predator foraging mode and hunting success at the individual level with an online videogame

**Short title:** Predator-prey interactions in virtual worlds.

# Lay summary {.unnumbered}

Identifying the behavioral mechanisms underlying predator success is critical to accurately predicting how predators impact prey populations. Because behaviors are often difficult to study in natural systems, we used an online videogame that simulates predator-prey interactions. Our study demonstrates that while predators display a variety of hunting strategies driven by prey behavior, each strategy was equally successful.

# Abstract {.unnumbered}

Predator-prey interactions are important drivers of community and ecosystem dynamics. With an online multiplayer videogame, we propose a novel system to explore within-population variation in predator hunting mode, and how predator-prey behavioral interactions affect predator hunting success. We empirically examined how four predator foraging behaviors covary at three hierarchical levels (among environments, among individuals, and within individuals) to assess the structure of predator hunting mode. We also investigated how prey activity affects the foraging behavior and hunting success of predators. Our study supports key findings on predator foraging mode and predator-prey interactions from behavioral ecology. We found that individual predators displayed a diversity of hunting tactics that were conditioned by prey behavior. With prey movement, individual predators specialized either as cursorial or ambush hunters along a continuum of their hunting traits, but also shifted their strategy between encounters. Both types of hunters were generally better against slower-moving prey, and they achieved similar prey captures over the sampling period. This suggests that virtual worlds supporting multiplayer online videogames can serve as legitimate systems to advance our knowledge on predator-prey interactions.

\vspace{12pt}
\vspace{12pt}

**Keywords:** individual specialization, environmental variation, hunting mode, hunting tactics, predator-prey interactions, online videogames.

\newpage
# Introduction {.unnumbered}

Predator hunting mode plays a crucial role in structuring ecological communities and ecosystems [@hueyEcologicalConsequencesForaging1981;@preisserPredatorHuntingMode2007;@schmitzEffectsPredatorHunting2008;@kersch-beckerCommunitywideResponsesPredation2018] and is usually described as 1) active/cursioral when hunters search, follow, and chase prey for long distances, 2) sit-and-pursue, when hunters remain motionless and pounce on prey that are within chasing distance, and 3) sit-and-wait/ambush, when hunters wait for prey to be within immediate capture distance [@mclaughlinSearchModesBirds1989]. Field studies show that contrasting hunting modes (e.g. cursorial vs ambush) found among and within predator species can lead to differences in the number of individuals or species, or in the type of prey captured [@donihueAegeanWallLizards2016;@glaudasForagingModeRelative2019;@millerFearMovePredator2014]. As a result, predators with contrasting hunting modes can cause opposing trophic cascades and act at different trophic levels [@schmitzEffectsPredatorHunting2008;@romeroContrastingCascadeEffects2011].

Predator species are often classified either as active or sit-and-wait hunters based on their average behavior [@limaPuttingPredatorsBack2002;@Miles.etal2007;@pettorelliChapterTwoIndividual2015;@schmitzPredatorPreyFunctional2017]. While such categorisation has proven useful to predict community and ecosystem dynamics [@Wirsing.etal2021], it ignores the complexities of predator foraging decision-making. Indeed, growing evidence suggests that behavioral variation among individual predators can have important consequences for predator-prey interactions [@pettorelliChapterTwoIndividual2015;@toscanoPersonalityForagingBehavior2016;@schmitzPredatorPreyFunctional2017]. For instance, individual predator behavioral type can mediate consumptive and non-consumptive effects during trophic interactions [@Smith.Blumstein2010;@griffenRoleIndividualBehavior2012;@toscanoTraitmediatedFunctionalResponses2014]. Yet, the extent to which predators within populations differ in their foraging mode and how these individual differences affect the outcome of predator-prey interactions remain unclear. It is therefore imperative that we quantify and account for individual variation in hunting mode during predator-prey interactions if we hope to understand the community consequences of predation.

Stable individual differences in hunting mode within populations can be driven by specialization when individuals experience temporal and/or spatial fluctuations in the distribution, availability, or behavior of their prey [@araujoEcologicalCausesIndividual2011;@carneiroMethodsDetectingQuantifying2017;@courbinShorttermPreyField2018;@phillipsCausesConsequencesIndividual2017]. For instance, individual predators can specialize in specific tactics to meet the energy/time demands required to successfully capture the type of prey generally encountered [@bowenPreydependentForagingTactics2002;@tinkerFoodLimitationLeads2008;@arthurSouthWinterWithindive2016]. According to the foraging syndrome hypothesis, these tactics are characterized by a continuum of coordinated morphological, physiological, and behavioral traits that are expressed by a predator to subdue its prey [@perryForagingModeLacertid1990;@perryEvolutionSearchModes1999;@butlerForagingModeChameleon2005;@cooperForagingModeControversy2005;@Miles.etal2007]. The activity and movement patterns of prey are major drivers of encounter rates with predators [@gerritsenEncounterProbabilitiesCommunity1977;@hueyEcologicalConsequencesForaging1981;@scharfEfficiencyEvaluationTwo2006], which may therefore lead to nonrandom interactions between predator-prey behavioral types [@wolfAnimalPersonalitiesConsequences2012]. For example, the locomotor crossover hypothesis [@hueyEcologicalConsequencesForaging1981] predicts that ambush predators should be more successful when they hunt fast-moving prey, while cursorial predators should have greater success with sedentary prey [@belgradPredatorPreyInteractions2016;@donihueAegeanWallLizards2016;@scharfEfficiencyEvaluationTwo2006]. Thus, in the presence of prey with diverse movement patterns, individual predators specializing in contrasting hunting modes might coexist within a population if they achieve similar hunting success [@araujoEcologicalCausesIndividual2011;@changPredatorPersonalityPrey2017].

Habitat structure is a second important driver of predator foraging mode, as it shapes opportunities for prey encounter and prey capture [@robinsonForagingBehaviorForest1982;@jamesEffectsHabitatComplexity1994;@Sargeant.etal2007;@wasiolkaBehaviouralResponsesLizard2009;@donihueAegeanWallLizards2016]. A growing body of evidence points to predators who hunt in open and homogeneous habitats adopting a cursorial strategy, contrary to those hunting in heterogeneous and closed habitats that typically ambush their prey [@jamesEffectsHabitatComplexity1994;@wasiolkaBehaviouralResponsesLizard2009;@donihueAegeanWallLizards2016]. Hence, the habitat components of a predator's hunting grounds can shape its hunting tactic. Heterogeneous habitats are expected to favor sit-and-wait/sit-and-pursue hunters as they offer perches and cover, which are useful for ambushes [@jamesEffectsHabitatComplexity1994;@laurelInfluenceCruisingAmbush2006]. On the contrary, active hunters should benefit from higher encounter rates in open habitats as prey detection is easier, although, at the expense of being themselves more easily detected [@michelDifferentialEffectsStructural2009]. This suggests that habitat structure could mediate tradeoffs between hunting strategies.

Trophic interactions are dynamic processes that can also trigger flexible behavioral adjustments by individual predators [@helfmanModeSelectionMode1990;@heithausFeedingStrategiesTactics2018]. Predators can shift their hunting strategy in response to changes in prey density and heterogeneity [@inoueForagingStrategyMantid1983;@wooIndividualSpecializationDiet2008], prey behavioral type [@mcgheeReciprocalBehavioralPlasticity2013], prey condition [@Wignall.Taylor2008], seasonality [@Miles.etal2007;@phillipsCausesConsequencesIndividual2017], or habitat structure [@wasiolkaBehaviouralResponsesLizard2009]. Foraging mode shifts might thus be crucial for predators to maintain capture rates when coping with prey antipredator behavior and environmental change [@laurelInfluenceCruisingAmbush2006].

Longitudinal studies on predator-prey interactions often involve considerable financial, technical, and ethical challenges, especially when studying larger or elusive wildlife such as apex predators [@hertelGuideStudyingAmongindividual2020]. For instance, a major challenge impeding empirical investigations of individual variation in hunting mode is the need for repeated behavioral measurements of numerous individuals in varying environmental settings [@Dall.Griffith2014;@dingemanseCriteriaAcceptableStudies2020]. This also comes with the difficulty of identifying traits in predators and prey that are easily observable and ecologically relevant. Besides, numerous predator-prey studies are conducted under controlled laboratory conditions that may fail to capture the nuances and complexities of a predator's behavior in the wild [@Carter.etal2013;@Niemela.Dingemanse2014]. Consequently, few studies have investigated how prey movement shapes predator foraging syndromes at multiple hierarchical levels (i.e. within and among individuals or habitats) along with the relative importance of predator and prey behaviors for predator hunting success.

Here, we propose a novel approach to circumvent these challenges by studying individual variation in predator behavior that capitalizes on online multiplayer videogames [@ahmadProblemPredictingReal2014;@balicerModelingInfectiousDiseases2007;@lofgrenUntappedPotentialVirtual2007;@oultramVirtualPlaguesRealworld2013;@rossVirtualWorldsLaboratories2015]. Online multiplayer videogames could provide numerous opportunities for ecologists to study general ecological phenomena, including the mechanisms driving individual variation in behavior [@Barbe.etal2020;@Beauchamp2020;@Duthie.etal2021;@CERE2021105]. First, online videogames provide abundant repeated measurements on millions of individual players across temporal and environmental gradients. Second, the structure of the virtual environment is known and can be used to evaluate how specific components affect the behavior of interest. Third, videogames can reproduce realistic ecological settings in which complex interactions occur among players. A classic example is the case of the "Corrupted Blood" epidemic in *World of Warcraft*, where transmission modes/vectors and human reactions to the disease were surprisingly similar to what would be expected in a real-world outbreak [@balicerModelingInfectiousDiseases2007;@lofgrenUntappedPotentialVirtual2007]. For these reasons, online multiplayer videogames could potentially complement traditional field studies, and thus allow us to bridge the gap between real-world ecological studies and large-scale computer simulations [@rossVirtualWorldsLaboratories2015].

We used the videogame *Dead by Daylight* (*DBD*) as our study system. *DBD* is an asymmetrical online multiplayer horror game that pits a single player (predator) against a group of four players (prey). The predator's main objective is to search for and consume prey (Figure 1A), whilst the preys' objective is to exploit resources while avoiding the predator. These resources consist of generators that need to be repaired so prey can escape and win. Thus, analogous to real prey that move across patches to exploit resources under predation risk, prey in *DBD* must move around the virtual environment and locate generators to repair (Figure 1B). As described in classical ecological studies of patch use [@Brown1988;@Brown1999;@Kotler.Blaustein1995], prey must be wary of the time they spend repairing a generator (i.e. foraging in a patch) because investing too much time can increase the risks of being captured. Prey players can use a wide range of behaviors such as cooperation or hiding [@CERE2021105] to successfully escape (Figure 1 B-C), providing opportunities for the predator to express a diversity of hunting tactics. Moreover, each match in *DBD* occurs within a specific virtual habitat such as forests, farmlands, and urban areas. These environments differ in their structure [@mccoyHabitatStructureEvolution1991], such as in the availability of perches and refugia, vegetation density, or surface area (Figure 1D). Predator players can exploit these habitat features to hunt their prey. Hence, they experience variability in the prey and habitats that they encounter, and are expected to benefit from changing their behavior accordingly to maximize hunting success. Lastly, although *DBD* is a virtual environment, we suggest that individual players express ecologically relevant decisions in response to predation or prey behavior, and the resulting complex interactions that are monitored can be valuable for ecological research. Therefore, an empirical approach can be adopted to study the player population [see these studies for examples on other games: @Szell.etal2010;@Fuchs.Thurner2014;@Belaza.etal2020], with methods equivalent to those used in observational studies of natural predators.

In this study, we use an extensive dataset on the hunting behavior of predator players in *DBD* to empirically investigate environmental and individual variation in hunting mode, and how predator and prey behavior affect prey capture. We use four hunting-related behaviors as proxies of hunting mode: travel speed, the rate of space covered in the environment, the time spent guarding captured prey, and the time elapsed before the first prey capture. Predators adopting a cursorial hunting mode should travel faster and cover more space in the environment, but should spend less time guarding and have a shorter latency before the first capture. Predators with an ambush hunting mode should exhibit the opposite tendency. Thus, both strategies should represent the extremes of a continuum. We use multivariate mixed-modelling to quantify variation in these behaviors and their correlations as a way to decompose the hunting mode continuum at different hierarchical levels within the predator population [@dingemanseQuantifyingIndividualVariation2013]. These levels include behavioral differences among environments, consistent differences among individuals in their average hunting behavior, and differences arising from individuals adjusting their behavior over time in response to temporal changes in environmental conditions or prey behavior. First, we hypothesize that habitats shape the hunting mode employed by predators. If there are among environmental behavioral differences, we expect correlated trait values associated with an ambush mode in smaller and heterogeneous environments, and correlated trait values associated with a cursorial mode in open/wider and homogeneous environments (i.e. among-environment behavioral correlations). Second, we hypothesize that individual predators will consistently differ in their hunting mode over time, with some specializing as cursorial hunters and others as ambush hunters. Thus, if predators differ in their average behaviors, we predict that their average trait values will be positioned along an ambush-cursorial continuum (i.e. among-individual behavioral correlations), where the position designates their preferred hunting mode. Third, we expect that individual predators will switch from cursorial to ambush tactics between foraging bouts (i.e. between matches). If there is within-individual behavioral variation, we predict negative relationships between hunting behaviors at this level (i.e. within-individual behavioral correlations). Fourth, following the locomotor crossover hypothesis, we predict that ambush and cursorial predator types will coexist in the population because both achieve similar hunting success by performing better against prey with the opposite locomotor tendency.

# Materials and methods {.unnumbered}

## Study system

The datasets used to test our hypotheses were provided by Behaviour Interactive Inc., the owner and developer of *DBD*. The company records the behavior of players for every match played online. During our study period, *DBD* offered 15 playable predator avatars. Players who adopt the predator's role choose their avatar before a match. Each predator avatar has unique abilities that may encourage different playstyles. Some have abilities that make them stealthier, while others can run faster, or have more powerful attacks. We thus controlled for the chosen avatar in our models since it may impact the playstyle of the predator player. In addition, the game environment where players compete is usually randomly assigned from a list of 27 maps differing in their physical components. For example, some maps have large playable surface areas with low vegetation density, which may favor the use of a cursorial strategy. Other maps have a smaller surface area with high vegetation density, which may impair visibility and alter prey detection, favoring the use of an ambush strategy. However, an important game feature to consider is that predators have constant visual cues that display the location of the generators. This could interfere with how the virtual environment affects the predator's behavior or hunting success. For instance, predators might use these cues to approximate the distance/time required to travel between generators, which may relax the energy/concentration allocated to managing movement across the environmental features. For additional details on the game settings and map characteristics, refer to https://deadbydaylight.com/en, and https://deadbydaylight.gamepedia.com/Dead_by_Daylight_Wiki.

## Data collection

The game developer provided us with raw datasets ranging from 20 March to 17 June 2019. Because the company records player data with automated scripts, technical issues or errors in the data compilation can occur. For instance players hacking the game or disconnecting during a match, among other reasons, can cause errors in the data compilation. We thus had to combine these datasets and apply filtering, cleaning, and verification procedures to obtain our synthetic dataset. First, we filtered for matches that were played exclusively against a group of unknown people. Second, we retained matches that lasted more than five minutes, as short matches are usually interrupted because of disconnections or inactive players, and deleted any match where the match duration was missing or equal to zero. Third, we removed matches where predator players were obviously inactive, that is, when they had average speeds of, or very close to, zero while staying within a maximum of two squares or less during the match. Fourth, based on our knowledge of the game, we deleted any matches where the observed behaviors were extreme and were most likely the result of hacking or players doing something different to how the game is intended to be played (e.g. farming for points).

Our synthetic dataset consists of a population of 2 378 new anonymous players who initiated their first match between 20 March and 22 March, with a total record of 77 047 matches (average: `r toString(round(mean(data$total_matches), digits = 0))` matches per individual, range: `r toString(min(data$total_matches))` - `r toString(max(data$total_matches))` matches). The average match duration was `r toString(format(round(mean(data$game_duration)/60, digits = 2), nsmall = 0))` minutes (range: `r toString(format(round(min(data$game_duration)/60, digits = 2), nsmall = 0))` - `r toString(format(round(max(data$game_duration)/60, digits = 2), nsmall = 0))` minutes). For every match, the date (date-hour-minutes), the duration (seconds), the predator player's anonymous ID, the predator's avatar, and the game environment were recorded along with the predator and prey behaviors.

## Behavioral traits

We ran a principal components analysis on eight behavioral traits to identify the presence of structured hunting tactics in the predator player population (see Figure S1 and Table S1 in the Supporting information). We then selected four behaviors that summarized most of the variation in the observed tactics for all our analyses. We used this approach to ease the interpretation of the trait correlations in the multivariate models and allow the reuse of our variables in future analyses. In fact, any new sample of observations would yield a different ordination with different principal components, precluding any comparison between studies. The behaviors we selected were the average travel speed (m/s) (mean = `r toString(format(round(mean(data$speed, na.rm = TRUE), digits = 2), nsmall = 2))`, sd = `r toString(format(round(sd(data$speed, na.rm = TRUE), digits = 2), nsmall = 2))`), the rate of space covered (square/s) (mean = `r toString(format(round(mean(data$space_covered_rate, na.rm = TRUE), digits = 2), nsmall = 2))`, sd = `r toString(format(round(sd(data$space_covered_rate, na.rm = TRUE), digits = 2), nsmall = 2))`), the total amount of time spent guarding captured prey (mean = `r toString(format(round(mean(data$prox_mid_PreyGuarding, na.rm = TRUE), digits = 2), nsmall = 2))`, sd = `r toString(format(round(sd(data$prox_mid_PreyGuarding, na.rm = TRUE), digits = 2), nsmall = 2))`), and the time predators took to capture their first prey (mean = `r toString(format(round(mean(data$hook_start_time, na.rm = TRUE), digits = 2), nsmall = 2))`, sd = `r toString(format(round(sd(data$hook_start_time, na.rm = TRUE), digits = 2), nsmall = 2))`).

Our proxies of activity were the predator's average travel speed defined as the average number of meters per second traveled during a match, and space coverage defined as the number of 16x16 meters squares entered per second in a grid that covers the whole virtual environment [similar to measures of activity in open field tests, @Montiglio.etal2010]. The grids are drawn by the game developer to build the game environments, but are invisible to the players. Based on these data, we divided the number of times a square was visited by the match duration to obtain the rate of space covered. Unfortunately, it was not possible to know which specific square was visited, so our variable is a raw estimate of the rate at which predators cover space in the environment. The time spent guarding prey describes the time a predator spent monitoring near capture sites to ambush prey players trying to rescue individuals that were captured. This trait is measured by drawing (invisible) 9-meter radius circles around all sites where the predator brings prey to be consumed (each site is at the center of a circle). Thus, whenever a predator brought prey to a capture site during a match, the time (in seconds) it spent monitoring within the site's circle area was recorded. We could then sum all the events where predators were monitoring capture sites to obtain the total amount of time spent guarding captured prey during a match. Lastly, the time before the first capture was calculated as the amount of seconds elapsed before a predator captured its first prey.

To test the locomotor crossover hypothesis, we were provided datasets that contained the average travel speed (m/s) and rate of space covered (square/s) of all the prey players for each match played by the predator. Both traits are measured using the same method described for predators. For both prey behaviors, we averaged the four individual prey player values within each match since we were interested in the average effect of prey behavior on the predator's hunting behavior and success. Thus, we used one average value per prey behavior for each match played by the predator.

## Statistical analyses: Software and computer setup

We performed all statistical analyses using R (version 4.1.2, R Core Team, 2021) on a remote computer cluster (Cedar, Compute Canada, https://docs.computecanada.ca/wiki/Cedar) running on CentOS Linux 7. All models were fitted using the R package 'brms' version 2.16.3 [@burknerBrmsPackageBayesian2017]. To ensure a minimum of reproducibility and transparency, we made all the data, R code, most outputs, and the R sessions information publicly available (https://github.com/quantitative-ecologist/predator-foraging-mode-videogames).

## Statistical analyses: Variation in hunting mode

We first parametrized a Bayesian multivariate mixed model [@dingemanseQuantifyingIndividualVariation2013;@Burkner2018;@mitchellContextdependentTraitCovariances2020] (for an overview using 'brms', see https://paul-buerkner.github.io/brms/articles/brms_multivariate.html) to quantify the repeatability of hunting behavior, and to evaluate among-environment, among-individual (specialization), and within-individual (flexibility) behavioral correlations. For each hunting behavior, we controlled for the predator's population-response to prey behavior by adding the prey travel speed ($x_1$) and rate of space covered ($x_2$) as linear fixed effects. We also included the square-root of the match duration ($x_3$) as a fixed effect for the time spent guarding and the time before the first capture to control for differences in game length. We log transformed the time spent guarding and the time before the first capture to achieve normality and then defined each behavior ($y1$ = speed, $y2$ = space, $y3$ = guarting time, $y4$ = time 1^st^ capture) as having a Gaussian distribution. All behaviors were then standardized to mean and unit variance (z-scores). The model is described by the following equations:

\[
%I need to manually create tables in word to insert the equations and add equation number
\begin{align}
y1_{ghij} &= \text{ } (\beta_{0y1} + env_{0y1,g} + avatar_{0y1,h} + id_{0y1,i}) \\ 
&\text{ } + \text{ } \beta_{1y1} x_1 + \beta_{2y1} x_2 + \varepsilon_{0y1,ghij}
\end{align}
\]

\[
\begin{align}
y2_{ghij} &= \text{ } (\beta_{0y2} + env_{0y2,g} + avatar_{0y2,h} + id_{0y2,i}) \\
& \text{ } + \text{ } \beta_{1y2} x_1 + \beta_{2y2} x_2 + \varepsilon_{0y2,ghij}
\end{align}
\]

\[
\begin{align}
y3_{ghij} &= \text{ } (\beta_{0y3} + env_{0y3,g} + avatar_{0y3,h} + id_{0y3,i}) \\
&\text{ }  + \text{ } \beta_{1y3} x_1 + \beta_{2y3} x_2 + \varepsilon_{0y3,ghij}
\end{align}
\]

\[
\begin{align}
y4_{ghij} &= \text{ } (\beta_{0y4} + env_{0y4,g} + avatar_{0y4,h} + id_{0y4,i}) \\
&\text{ } + \text{ } \beta_{1y4} x_1 + \beta_{2y4} x_2 + \varepsilon_{0y4,ghij}
\end{align}
\]

where *g* indexes the environment, *h* the predator avatar, *i* the individual player, and *j* the recorded match. The game environment ($env_{0y,g}$), the predator avatar ($avatar_{0y,h}$), and the player ID ($id_{0y,i}$) are random intercepts (among- environment, avatar, and individual variances), and ($\varepsilon_{0y,ghij}$) are the residuals (within-individual variance). Random intercepts and residuals were assumed to follow a multivariate Gaussian distribution with their associated variance-covariance matrices ($\Omega_{env}$, $\Omega_{avatar}$, $\Omega_{id}$, $\Omega_{\varepsilon}$) (equations S1-S4 in the Supporting information). For each combination of behaviors ($y_n$), we extracted the behavioral correlations among environments ($r_{env_{0,y_n}env_{0,y_n}}$), individuals ($r_{id_{0,y_n}id_{0,y_n}}$), as well as within-individual behavioral correlations ($r_{\varepsilon_{0,y_n}\varepsilon_{0,y_n}}$) [@dingemanseQuantifyingIndividualVariation2013]. The sample size of each parameter's posterior distribution is 1000 (see section 'Parametrization of the Bayesian multivariate mixed-model' in the Supporting information for details).

## Statistical analyses: Effect of hunting behavior and prey behavior on prey capture

We first quantified the linear relationship between hunting success and predator behavior by fitting a Bayesian generalized linear mixed model. Since predators can capture a maximum of four prey, we fitted the model using the number of prey captured per total number of prey in a match (four) as a binomial response variable ($\omega_{hij}$ ~ $Binom(max_{hij}, P_{hij})$) with a logit link function. The model fits a linear function ($\beta_{n,pred} \textit{x}_{hi}$) where we could estimate if hunting success increased or decreased with increasing hunting behavior scores. We fitted the mean probability of capturing four prey ($P_{hij}$) in the environment *h* for individual *i* on its *j* match as a function of its travel speed, rate of space covered, time spent guarding, and latency before the first capture (equation S5 in the Supporting information). We computed a second model to account for variation in hunting success explained by prey behavior ($\beta_{n,prey} \textit{x}_{hi}^{'}$). We thus added prey travel speed and their rate of space covered in the model equation (equation S6 in the Supporting information). Both models had random intercepts for the game environment ($env_{0,h}$) and the predator player's ID ($id_{0,i}$) to partition the variance in hunting success explained by differences among players and the environments where matches occurred. The random intercepts for the game environment and the predator player ID were assumed to follow a Gaussian distribution with estimated variance ($env_{0,h}$~$N(0,V_{env})$, $id_{0,i}$~$N(0, V_{id})$). We included an observation-level random effect to account for overdispersion and compared the models to a beta-binomial model to ensure that the estimates were robust [@harrisonComparisonObservationlevelRandom2015]. Trait values were standardized to mean and unit variance (z-scores). The sample size of each parameter's posterior distribution is 1000 for both models.

We built a third model with the same structure as the first model and included quadratic terms ($\frac{1}{2} \gamma_{n,pred} \textit{x}_{hi}$), identified as lambda, to determine whether the relationships between hunting success and predator behavior are concave or convex (equation S7 in the Supporting information). Concave gradients suggest that individuals at the extremes of the trait distribution perform poorly while the opposite is true when the gradient is convex [@brodieVisualizingQuantifyingNatural1995]. We also added interaction terms for each combination of predator traits ($\gamma_{n,pred}$) to estimate correlated effects on hunting success. Lastly, we computed a fourth model with the same structure as the third and included quadratic terms for prey behavior ($\frac{1}{2} \gamma_{n,prey} \textit{x}_{hi}^{'}$), and interaction terms between predator and prey behaviors ($\gamma_{n, \textit{pred prey}}$) to test if predators perform better against prey with the opposite locomotor tendency (locomotor crossover) (equation S8 in the Supporting information). All trait values were standardized to mean of 0 and unit variance (z-scores). The sample size of each parameter's posterior distribution is 1000 for both models. For the four models, we included the square-root of the match duration as a fixed effect to control for differences in game length. We provide a detailed description of the model parametrization in the supporting information ('Parametrization of the Bayesian mixed-models for hunting success').

We performed approximate leave-one-out cross-validation using Pareto smoothing importance sampling (PSIS-LOO) [@Vehtari.etal2017] with the 'loo' function in 'brms' to select the best out of the four candidate models. This method outlines the best model by comparing their predictive accuracy based on the difference of their expected log predictive density (elpd). The model with the highest elpd value should thus be the best at predicting the data. We also computed the marginal ($R_{marginal}^2$) and conditional ($R_{conditional}^2$) coefficients of determination [@nakagawaCoefficientDeterminationR22017] of all the candidate models to assess the relative contribution of the predator behavior, the prey behavior, the behavioral interactions, and the random effects (differences among individuals and environments) on the predator's hunting success. We assumed that the relationship between hunting behavior and hunting success reached statistical significance when the 95% credible intervals of the fixed parameter values did not overlap zero [@Nakagawa.Cuthill2007].

## Variance decomposition {.unnumbered}

Following the method by @nakagawaRepeatabilityGaussianNonGaussian2010 for Gaussian response models, we calculated each hunting trait's adjusted repeatability estimate (intra-class correlation coefficient, *ICC*) for the game environment, the predator avatar, and the predator player ID. To do so, we divided the mean variance ($V$) drawn out of the 1000 posterior samples of each specific random effect by the total behavioral variance (e.g. $ICC_{id_{y1}} = V_{id_{0,y1}} / (V_{env_{0,y1}} + V_{avatar_{0,y1}} + V_{id_{0,y1}} + V_{\varepsilon_{0,y1}})$). We computed the 95% credible intervals for each repeatability estimate using the highest posterior density intervals. We additionally calculated the *ICC* of the predator hunting success for the player ID and the game environment using the method by @nakagawaCoefficientDeterminationR22017 for binomial models and computed their 95% credible intervals using the highest posterior density intervals.

# Results {.unnumbered}

## Variation in hunting mode: Repeatability of hunting behaviour

Contrary to our predictions, neither the average travel speed ($ICC_{env_{y1}}$ [95% CI] = 0.002 [0.001, 0.003]), nor the proportion of time spent ambushing ($ICC_{env_{y3}}$ [95% CI] = 0.002 [0.001, 0.003]) differed among the game environments (figure 2B, diagonal). We detected small differences among the game environments in the average rate of space covered ($ICC_{env_{y2}}$ [95% CI] = 0.065 [0.036, 0.097]) and time before the first capture ($ICC_{env_{y4}}$ [95% CI] = 0.055 [0.029, 0.082]) (figure 2B, diagonal). 

Predator avatars differed slightly in their average travel speed ($ICC_{avatar_{y1}}$ [95% CI] = 0.091 [0.042, 0.153]. Predators displayed weak differences between the avatars for the other three hunting behaviors  ($ICC_{avatar_{y2}}$ [95% CI] = 0.025 [0.010, 0.046], $ICC_{avatar_{y3}}$ [95% CI] = 0.034 [0.012, 0.064], $ICC_{avatar_{y4}}$ [95% CI] = 0.021 [0.008, 0.039]).

As predicted, we found moderate among-individual differences in average travel speed ($ICC_{id_{y1}}$ [95% CI] = 0.280 [0.254, 0.304]) and average proportion of time spent ambushing ($ICC_{id_{y3}}$ [95% CI] = 0.322 [0.301, 0.342]), while individuals differed weakly in their time before the first capture ($ICC_{id_{y4}}$ [95% CI] = 0.102 [0.091, 0.114]) (figure 2A, diagonal). Individual predators differed weakly in their average rate of space covered ($ICC_{id_{y2}}$ [95% CI] = 0.051 [0.044, 0.057]) (figure 2A, diagonal).

## Variation in hunting mode: Correlations between hunting behaviours

Environments where predators were on average faster were also those where they spent on average less time ambushing their prey ($r_{env_{0,y1}env_{0,y3}}$ [95% CI] = -0.465 [-0.767, -0.143]) (figure 2A, lower off-diagonal). We detected a similar relationship between space coverage and time spent ambushing, although it was not statistically significant as the credible intervals overlapped zero ($r_{env_{0,y2}env_{0,y3}}$ [95% CI] = -0.246 [-0.582, 0.071]). Predators took on average less time to capture their first prey in environments where they covered space at a faster rate ($r_{env_{0,y2}env_{0,y4}}$ [95% CI] = -0.830 [-0.937, -0.702]), while taking more time on average in environments where they used ambushes ($r_{env_{0,y3}env_{0,y4}}$ [95% CI] = 0.354 [0.025, 0.650]) (figure 2A, lower off-diagonal). Lastly, we did not detect among-environment correlations between travel speed and space coverage, or between travel speed and the time before capturing a first prey ($r_{env_{0,y1}env_{0,y2}}$ [95% CI] = -0.045 [-0.404, 0.291], ($r_{env_{0,y1}env_{0,y4}}$ [95% CI] = 0.079 [-0.273, 0.419]) (figure 2A, lower off-diagonal).

As we expected, the predators’ average travel speed and proportion of time spent ambushing were negatively correlated ($r_{id_{0,y1}id_{0,y3}}$ [95% CI] = -0.635 [-0.671, -0.597]). Thus, faster predators spent less time ambushing prey (figure 2B, lower off-diagonal). Faster individuals covered space at a faster rate ($r_{id_{0,y1}id_{0,y2}}$ [95% CI] = 0.363 [0.297, 0.434]), and individuals who were faster or covered space at a faster rate also took less time to capture their first prey ($r_{id_{0,y1}id_{0,y4}}$ [95% CI] = -0.412 [-0.470, -0.350], $r_{id_{0,y2}id_{0,y4}}$ [95% CI] = -0.249 [-0.331, -0.163]) (figure 2B, lower off-diagonal). There was no relationship between space covered and time spent ambushing ($r_{id_{0,y2}id_{0,y3}}$ [95% CI] = 0.001 [-0.075, 0.079]), but ambush hunters required more time to capture their first prey ($r_{id_{0,y3}id_{0,y4}}$ [95% CI] = 0.244 [0.177, 0.310]) (figure 2B, lower off-diagonal).

At the residual within-individual level, we detected a weak positive correlation between travel speed and the rate of space covered ($r_{\varepsilon_{0,y1}\varepsilon_{0,y2}}$ [95% CI] = 0.191 [0.184, 0.198]) and a negative correlation between travel speed and the proportion of time spent ambushing prey ($r_{\varepsilon_{0,y1}\varepsilon_{0,y3}}$ [95% CI] = -0.289 [-0.296, -0.282]) (figure 2B, upper off-diagonal). Hence, matches in which a predator was faster (relative to its average) were also matches in which it covered space at a faster rate, while spending less time ambushing prey. Predators that covered space at a faster rate also took more time before capturing their first prey ($r_{\varepsilon_{0,y2}\varepsilon_{0,y4}}$ [95% CI] = 0.135 [0.127, 0.142]) (figure 2B upper off-diagonal). We did not detect large correlations between travel speed or time spent ambushing and the time before the first capture ($r_{\varepsilon_{0,y1}\varepsilon_{0,y4}}$ [95% CI] = -0.080 [-0.088, -0.073], $r_{\varepsilon_{0,y3}\varepsilon_{0,y4}}$ [95% CI] = -0.097 [-0.105, -0.090]).

## Effect of predator and prey behaviour on hunting success: Linear relationships

Predator behavior alone (equation S5) explained 12.7% of the variation in hunting success ($R_{marginal}^2$ = 0.127). Travel speed and time spent ambushing were positively related to hunting success (table 1), suggesting that faster predators and ambush predators captured more prey (figure 3A, C). Predators who covered space at a faster rate captured fewer prey (table 1) (figure 3B). Predators that required more time to capture their first prey had lower hunting success (table 1) (figure 4D). Hunting success barely varied among game environments ($ICC_{env}$ [95% CI] = 0.005 [0.002, 0.008]). Differences among individuals in hunting success were low ($ICC_{id}$ [95% CI] = 0.067 [0.060, 0.074]).

Adding prey behavior (equation S6) increased the explained variance in hunting success to 18% ($R_{marginal}^2$ = 0.181). Predators that competed against cursorial prey had significantly lower hunting success (table 1). Prey that were faster at covering space in the environment significantly reduced the predators' hunting success (table 1).

```{r, eval = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
# ========================================================

#               Code to produce Table SII

# ========================================================

# Load libraries
library(data.table)
library(flextable)
library(officer)
library(dplyr)


# ========================================================
# Prepare the table
# ========================================================

# Load the coefficient table
table <- readRDS(here::here("outputs", "05_hunting_success_coef-table.rds"))

# Round values to 2 digits
table[, c("Estimate", "Q2.5", "Q97.5") := 
        lapply(.SD, function (x) format(round(x, digits = 2), nsmall = 2)),
      .SDcols = c(2:4)]

# Compute the CI column
table[, "CI" := apply(cbind(Q2.5, Q97.5),
                      1, function(x) paste(sort(x), collapse = ", "))]

table[, "CI2" := paste("(", table$CI, sep = "")]
table[, "CI3" := paste(table$CI2, ")", sep = "")]
table[, c(3, 4, 6, 7) := NULL]
setnames(table, "CI3", "CI")

# Compute the estimate column
table[, Estimate := paste(table$Estimate, CI, sep = " ")][, CI := NULL]

# Reorder columns
setcolorder(table, neworder = c(3, 1, 2))

# Change coefficient names
coefficient1 <- list(
  "intercept",
  "speed",
  "space",
  "ambush",
  "time",
  "prey speed",
  "prey space",
  "speed",
  "space",
  "ambush",
  "time",
  "speed:space",
  "speed:ambush",
  "speed:time",
  "space:ambush",
  "space:time",
  "ambush:time",
  "prey speed",
  "prey space",
  "speed:prey speed",
  "speed:prey space",
  "space:prey space",
  "space:prey space",
  "ambush:prey speed",
  "ambush:prey space",
  "time:prey speed",
  "time:prey space"
)

table[, coefficient := coefficient1]

# ========================================================
# ========================================================



# ========================================================
#               Reshape the table for Word
# ========================================================

# Trait names
newtab <- table[2:7, 2]

# Predator trait interactions names
newtab <- rbind(newtab, table[12:17, 2])

# Pred-Prey interactions names
newtab <- rbind(newtab, table[20:27, 2])

# linear estimates
estimate1 <- c(table[2,3], table[3,3],
               table[4,3], table[5,3],
               table[6,3], table[7,3],
               rep("-", 14))

# Quadratic estimates
estimate2 <- c(table[8,3], table[9,3],
               table[10,3], table[11,3],
               table[18,3], table[19,3],
               rep("-", 14))

# Predator trait interactions estimates
estimate3 <- c(rep("-", 6), 
               table[12,3], table[13,3],
               table[14,3], table[15,3],
               table[16,3], table[17,3],
               rep("-", 8))

# Pred-prey interactions estimates 
estimate4 <- c(rep("-", 12), 
               table[20,3], table[21,3],
               table[22,3], table[23,3],
               table[24,3], table[25,3],
               table[26,3], table[27,3])

# Bind estimates
newtab <- cbind(newtab, estimate1 = estimate1,
                estimate2 = estimate2,
                estimate3 = estimate3,
                estimate4 = estimate4)

# ========================================================
# ========================================================



# ========================================================
# Compute the table for Word
# ========================================================

my_header1 <- data.frame(
  col_keys = c("coefficient", "estimate1",
               "estimate2", "estimate3", "estimate4"),
  line1 = c(" ", "Linear (95% CI)", 
            "Quadratic (95% CI)", "Pred Interaction (95% CI)",
            "Pred-prey Interaction (95% CI)"),
  stringsAsFactors = FALSE
)

# Custom theme
my_theme <- function(x, ...) {
    x <- colformat_double(x, big.mark = "'", decimal.mark = ",", digits = 1)
    x <- set_table_properties(x, layout = "fixed")
    x <- border_remove(x)
    std_border <- fp_border(width = 1, color = "black")
    x <- hline_top(x, part = "all", border = std_border)
    x <- hline_bottom(x, part = "all", border = std_border)
    autofit(x)
}

newtab %>%
  select(coefficient, estimate1, estimate2,
         estimate3, estimate4) %>%
  flextable(col_keys = my_header1$col_keys) %>%
  set_header_df(mapping = my_header1, key = "col_keys") %>%
  my_theme %>%
  merge_v(part = "header") %>%
  merge_h(part = "header") %>%
  align(align = "center", part = "all") %>%
  font(fontname = "Times new roman", part = "all") %>%
  fontsize(size = 10, part = "all") %>%
  align(align = "left", part = "body", j = 1) %>%
  height(height = .3) %>%
  width(j = c(1:5), width = 1.4) %>% # control table width
  hrule(rule = "exact") %>%
  set_caption("Table 1: Estimates of the models relating predator hunting success to predator hunting behavior, prey behavior, and their interactions.")
# ========================================================
# ========================================================
```

## Effect of predator and prey behaviour on hunting success: Quadratic relationships

Relative to the first model, the model that included quadratic and interaction terms for predator behavior (equation S7) barely increased the explained variance in hunting success ($R_{marginal}^2$ = 0.149). However, we observed significant concave relationships for travel speed and time spent ambushing (table 1), suggesting that hunting success was low at extreme behavioral values (figure 3E, G). There was a significant convex relationship between hunting success and space coverage (table 1) (figure 3F), and the shape of the quadratic function relating hunting success to time before the first prey is captured was almost the same as the linear function (figure 3H). Hunting success was still similar among game environments ($ICC_{env}$ [95% CI] = 0.010 [0.005, 0.016]), and varied slightly among individual players ($ICC_{id}$ [95% CI] = 0.072 [0.064, 0.079].

The model that included quadratic and interaction terms for predator and prey behavior (equation S8) had the highest explanatory power in hunting success ($R_{marginal}^2$ = 0.212). We detected concave relationships between hunting success and prey speed, as well as prey rate of space covered (table 1). Thus, predators had a higher probability of capturing all prey during a match when they competed against prey that expressed average population values of these traits.

## Effect of predator and prey behaviour on hunting success: predator and prey behavioural interaction

According to our predictions, faster predators were more successful when they competed against sedentary prey (figure 4A). Predators had higher hunting success for the whole range of values of space covered when they competed against slower-moving prey (figure 4C). Contrary to our expectations, the most successful predators where those who covered space at a slow rate when they competed against prey that were slower at covering space in the environment (figure 4D). However, those who covered space at the fastest rate where more successful against prey that were the slowest at covering space (figure 4D). There were no significant interactions between predator and prey travel speed (figure 4B). Lastly, for the whole range of time spent ambushing prey, predators had generally higher success against slower moving prey and prey that covered less space in the environment (figure 4E-F), although the interaction with prey space covered was not significant (table 1).

# Discussion {.unnumbered}

Our study uses an online multiplayer videogame to investigate individual variation in predator foraging mode, and how predator and prey behavior affect hunting success. We provide evidence that individuals who adopt the predator role display individual specialization and flexibility in their foraging modes, varying along a continuum from cursorial to sit-and-wait. The expression of these foraging modes was consistent with shifts in the expression of other behaviors such as space use and the latency to first prey capture, matching the predictions of the foraging syndrome hypothesis at the individual level. Contrary to our expectations, neither hunting behavior nor prey capture varied among game environments. Even if we found the presence of competing foraging modes in the population, the most successful predators were those who hunted at average population values of travel speed, and those who spent an above population-average of their time ambushing prey. Lastly, we found evidence for the locomotor-crossover hypothesis for some predator-prey trait combinations. However, predators were generally less successful when they competed against fast traveling prey and those who covered space faster in the environment.

Our analyses revealed that predators differed in their average travel speed and in their proportion of time spent ambushing prey. These behaviors were negatively correlated at the among-individual level, suggesting that individuals may specialize as either cursorial or ambush predators. Cursorial predators displayed a shorter latency to first prey capture compared to ambush predators. These results are similar to those of @mcgheeReciprocalBehavioralPlasticity2013, who found that fast moving northern pike (*Esox lucius*) were quicker to launch their initial attack. Interestingly, we found that hunting success decreased significantly with increasing latency to first capture, but did not strongly interact with time spent ambushing to affect hunting success. Thus, although ambush predators displayed a longer latency to capture their first prey, they were as successful as cursorial predators.

Since individuals achieved similar hunting success across the study period, our observations suggest that ecological mechanisms such as locomotor-crossovers may favor the coexistence of both foraging strategies within the *DBD* predator population. Indeed, we found that cursorial predators had greater hunting success when they competed against more sedentary prey, which agrees with empirical studies that tested the locomotor crossover hypothesis [@belgradPredatorPreyInteractions2016; @changPredatorPersonalityPrey2017; @donihueAegeanWallLizards2016]. However, locomotor-crossovers did not seem to explain the success of ambush predators, as they also displayed higher success against sedentary prey, or prey travelling at speeds close to the population average. In addition, predators reached similar hunting success across the observed range of space coverage and time spent ambushing (figure 4. C-F). A potential explanation is that by focusing solely on prey speed and space coverage, we failed to capture other important prey strategies involved in the predator-prey interaction. For instance, unpublished results by Santostefano et al. found four prey behavioral profiles in *DBD*, where faster and exploratory individuals seemed distinct from bolder individuals that performed more cooperative/altruistic actions, and that were involved in longer chases with the predator. Hence, we can hypothesize that the success of ambush predators might be explained, to a degree, by a higher capture of bold prey. Altogether, these non-random predator-prey interactions provide additional empirical evidence that predators (even within a virtual world) may select prey based on behavioral attributes that fit with their preferred foraging mode. Given that predator populations can be composed of multiple hunter-types that control the behavioral distributions of their prey, uncovering the functional link between foraging mode and prey preferences may elucidate how communities are assembled [@toscanoPersonalityForagingBehavior2016].

Predators also displayed flexibility in their foraging mode, where individuals switched between a cursorial or ambush strategy from one match to the other. These foraging mode switches were accompanied by shifts in space coverage and in the latency before the first capture, suggesting that predators may adjust their behavior according to the type of prey encountered. Thus, the outcome of the predator-prey interaction might not only be determined by the individual predator's preferred hunting mode, but also by its flexibility from one encounter to the next [@mcgheeReciprocalBehavioralPlasticity2013]. Although this falls outside the scope of this study, further analyses will need to investigate the dynamics of the predator behavior within a match to determine if predators switch between sit-and-wait to cursorial strategies as prey density is reduced [@inoueForagingStrategyMantid1983]. Short-term switches in hunting mode are also expected to occur as predators make behavioral adjustments in response to prey antipredator behavior [@helfmanModeSelectionMode1990], and should be favored when prey encounters are unpredictable [@wooIndividualSpecializationDiet2008; @carneiroMethodsDetectingQuantifying2017; @phillipsCausesConsequencesIndividual2017]. Comparing prey selection and capture rates between specialist and flexible hunters could provide important insight into the community-consequences of behavioral decisions made by predators.

An unexpected result in our study was that predator hunting mode did not change across different environments. This contrasts with studies showing that predators exploit habitat characteristics such as vegetation density to choose their hunting strategies [@jamesEffectsHabitatComplexity1994; @Warfe.Barmuta2004; @wasiolkaBehaviouralResponsesLizard2009]. A potential explanation is that habitat structure may have instead affected prey behavior, for instance, by altering their perception of predation risk or fear [@Heithaus.etal2009; @gaynorLandscapesFearSpatial2019]. Features of heterogeneous habitats can sometimes exert stronger predator cues, leading prey to avoid these habitats, or alter their activity to reduce predation risks [@preisserPredatorHuntingMode2007]. In a seperate analysis, we found that predator space coverage was largely explained by differences among game environments when prey behavior was excluded from the model (table S2, Supporting information), although the variance among game environments for the other traits remained the same. The observed differences in space coverage among the game environments were also not largely explained by differences in game environment surface area (table S2, Supporting information). Alternatively, it could be that the absence of environmental variance in predator behavior was caused by prey individuals differing in the way they respond to habitat changes, as some could have increased activity in heterogeneous habitats by exploiting refuges, thus, negating the effect of the environment on the predator's hunting strategy [@Warfe.Barmuta2004]. This could also explain why hunting success was similar among game environments. Another explanation is that predators could have altered their hunting behavior at larger scales according to prey behavior, but seek prey accessibility at finer scales by killing them in specific areas [@hopcraftPlanningSuccessSerengeti2005]. Ultimately, we cannot exclude the possibility that the game's design might not properly simulate real ecological habitats to affect the predator's behavior. For instance, one feature of the game's design is that predators have constant visual cues on the location of patches where prey forage. This offers them the opportunity to approximate the distance/time required to travel among patches, while possibly relaxing the energy/concentration allocated to managing movement across the habitat's features. Thus, further investigation is required to understand the scale at which the environment shapes predator behavior in this particular system.

We are among the first ecologists [Cere et al. accepted; @Barbe.etal2020] to use an online multiplayer videogame to investigate how ecological mechanisms shape the dynamics of trophic interactions. Virtual worlds are taking more and more place in our lives. Thus, understanding the ecology of virtual worlds and the patterns of our interactions within these will become an important topic of study. Beyond these considerations, we are persuaded that videogames are poised to play a central role in testing ecological hypotheses, as they reduce several challenges associated with empirical studies, while providing complex and ecologically-relevant datasets. However, videogames are not a panacea and they come with their own biases. Perhaps the most important one is that player behavior may not properly reflect behavioral decisions made by real-life organisms in the wild, as the player cannot "die" [@oultramVirtualPlaguesRealworld2013]. Hence, individuals may take greater risks in a videogame compared to natural predators [@lofgrenUntappedPotentialVirtual2007; @oultramVirtualPlaguesRealworld2013]. Moreover, while *DBD* provides an interesting system to investigate predator-prey interactions, prey density is fixed at four players, which prevents the modelling of predator functional responses. Lastly, similar to mesocosm experiments with single predators, the game may not reflect natural systems where multiple predator species compete for the same prey. In light of these potential biases, researchers should interpret results from online videogames with care, and aim to test specific ecological hypotheses when using virtual systems.

To conclude, individual variation in predator (and prey) behavior is recognized increasingly as a critical factor influencing the outcome of trophic interactions [@pettorelliChapterTwoIndividual2015; @toscanoPersonalityForagingBehavior2016; @Moran.etal2017]. Albeit our study being essentially descriptive, as it is the first to investigate individual variation in predator foraging behavior using an online videogame, we showed that individuals differed in contrasting hunting modes that align with those used by wild predators. These hunting modes varied among- and within- individuals along a continuum of correlated behaviors (foraging syndrome hypothesis). Thus, investigating correlated behaviors at different hierarchical levels can provide a more comprehensive understanding of a predator's foraging mode. Finally, our results suggest that predator-prey locomotor-crossovers may promote the coexistence of different predator and prey behavioral types. These results are important because they confirm that virtual worlds, when properly designed, can inform us on how ecological mechanisms drive observable phenomena, like prey preferences. We are confident that further studies using online videogames will provide valuable ecological insight for behavioral and community ecologists.

# Competing interests {.unnumbered}
The authors declare no competing interests

# Data availability statement {.unnumbered}

# Literature Cited {.unnumbered}

<div id="refs"></div>

